In [1]:
#As we dont have any GPU we will be using google collab for GPU usage
#Mout at drive 
import sys
from google.colab import drive
from pathlib import Path
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [13]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import warnings
warnings.filterwarnings("ignore")

In [4]:
#read the data
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/multi class bangla sentiment analysis/dataset/bangla_comments_tokenized.csv')
#rename  'not bully' to 'acceptable'
df['label'] = df['label'].replace({'not bully':'acceptable'})
#fill na values with zero
df = df.fillna(0)
df.tail()

           label  ... token_length
42031  religious  ...            5
42032     sexual  ...           11
42033  religious  ...            8
42034  religious  ...           21
42035  religious  ...            3

[5 rows x 6 columns]

In [12]:
# label encoding for output

sample_data = [2000,5000,10000,20000,30000,40000]

def label_encoding(category,bool):
  le = preprocessing.LabelEncoder()
  le.fit(category)
  encoded_labels = le.transform(category)
  labels = np.array(encoded_labels) # Converting into numpy array
  class_names =le.classes_ ## Define the class names again
  if bool == True:
    print("\n\t\t\t Label Encoding ","\nClass Names:",le.classes_)
    for i in sample_data:
      print(category[i],' ', encoded_labels[i],'\n')
    return labels

df.labels = label_encoding(df["label"],True)

			 Label Encoding
Class Names: ['Political' 'acceptable' 'religious' 'sexual']
acceptable   1

acceptable   1

religious   2

Political   0

acceptable   1

religious   2